function setVolume(c, a) { var b; if ("db" == a) { b = c.length = 0; for (var d = 23; -92 <= d; d -= .5) { c.length++; c.options[b].value = d; var e = 0 < d ? "+" : ""; d.toFixed(0) == d ? c.options[b].text = e + d + ".0 dB" : c.options[b].text = e + d + " dB"; b++ } c.length++; c.options[b].value = -100; c.options[b].text = "-\u221e dB" } else for (b = c.length = 0; 100 >= b; b++)c.length++, d = 100 - b, c.options[b].value = d, c.options[b].text = 0 === d ? "MIN" : 100 == d ? "MAX" : d }
function setMaxVolume(c, a) { var b; if ("db" == a) { b = c.length = 0; for (var d = 23; -40 <= d; d -= .5) { c.length++; c.options[b].value = d; var e = 0 < d ? "+" : ""; d.toFixed(0) == d ? c.options[b].text = e + d + ".0 dB" : c.options[b].text = e + d + " dB"; b++ } } else for (c.length = 0, b = 100; 13 <= b; b--)c.length++, d = b, c.options[100 - b].value = d, c.options[100 - b].text = 100 == d ? "MAX" : d }
function setSoundField(c, a) {
    for (var b = document.getElementById(c); b.hasChildNodes();)b.removeChild(b.firstChild); var d, e; a && !1 === a.last || (e = document.createElement("option"), e.value = "none", e.appendChild(document.createTextNode("Last Used")), b.appendChild(e), d = document.createElement("optgroup"), d.label = "--------------------", b.appendChild(d)); a && !1 === a["2ch"] && !1 === a.direct || (d = document.createElement("optgroup"), d.label = "2CH/DIRECT", a && !1 === a["2ch"] || (e = document.createElement("option"), e.value = "2ch",
        e.appendChild(document.createTextNode("2ch Stereo")), d.appendChild(e)), a && !1 === a.direct || (e = document.createElement("option"), e.value = "direct", e.appendChild(document.createTextNode("Direct")), d.appendChild(e)), b.appendChild(d)); a && !1 === a.afd || (d = document.createElement("optgroup"), d.label = "A.F.D.", e = document.createElement("option"), e.value = "afd", e.appendChild(document.createTextNode("Auto Format Decoding")), d.appendChild(e), b.appendChild(d)); a && !1 === a.dolby && !1 === a.neuralx || (d = document.createElement("optgroup"),
            d.label = "MOVIE", a && !1 === a.dolby || (e = document.createElement("option"), e.value = "dolby", e.appendChild(document.createTextNode("Dolby Surround")), d.appendChild(e)), a && !1 === a.neuralx || (e = document.createElement("option"), e.value = "neuralx", e.appendChild(document.createTextNode("Neural:X")), d.appendChild(e)), b.appendChild(d)); a && !1 === a.multi || (d = document.createElement("optgroup"), d.label = "MULTI STEREO", e = document.createElement("option"), e.value = "multi", e.appendChild(document.createTextNode("Multi Stereo")),
                d.appendChild(e), b.appendChild(d))
} function setEqualizer(c) { c = document.getElementById(c); for (var a = c.length = 0, b = 10; -10 <= b; --b)c.length++, c.options[a].value = b, c.options[a].text = 0 < b ? "+" + b + " dB" : b + " dB", a++ } function setLevel(c) { c = document.getElementById(c); for (var a = c.length = 0, b = 10; -10 <= b; b -= .5) { c.length++; c.options[a].value = b; var d = 0 < b ? "+" : "", e = b.toFixed(0) == b && 0 !== b ? ".0 dB" : " dB"; c.options[a].text = d + b + e; a++ } }
function setPresetGainLevel(c) { c = document.getElementById(c); for (var a = c.length = 0, b = 12; -12 <= b; b -= .5) { c.length++; c.options[a].value = b; var d = 0 < b ? "+" : "", e = b.toFixed(0) == b && 0 !== b ? ".0 dB" : " dB"; c.options[a].text = d + b + e; a++ } }
function setInputIcon(c) {
    c = document.getElementById(c); for (var a = [{ value: "bd", text: "BD Player" }, { value: "dvd", text: "DVD Player" }, { value: "bddvd", text: "BD/DVD Player" }, { value: "cd", text: "CD Player" }, { value: "tape", text: "TAPE Player" }, { value: "net", text: "NET Player" }, { value: "vcr", text: "VCR" }, { value: "turntable", text: "Turntable" }, { value: "stb1", text: "STB1" }, { value: "stb2", text: "STB2" }, { value: "tv", text: "TV" }, { value: "tuner", text: "FM/AM" }, { value: "game", text: "Game" }, { value: "camcorder", text: "Camcorder" }, {
        value: "camera",
        text: "Camera"
    }, { value: "mobile", text: "Mobile" }], b = c.length = 0; b < a.length; b++)c.length++, c.options[b].value = a[b].value, c.options[b].text = a[b].text
}
var _defaultStationNameTable = {
    "AMpreset1.name": "AM 1", "AMpreset2.name": "AM 2", "AMpreset3.name": "AM 3", "AMpreset4.name": "AM 4", "AMpreset5.name": "AM 5", "AMpreset6.name": "AM 6", "AMpreset7.name": "AM 7", "AMpreset8.name": "AM 8", "AMpreset9.name": "AM 9", "AMpreset10.name": "AM 10", "AMpreset11.name": "AM 11", "AMpreset12.name": "AM 12", "AMpreset13.name": "AM 13", "AMpreset14.name": "AM 14", "AMpreset15.name": "AM 15", "AMpreset16.name": "AM 16", "AMpreset17.name": "AM 17", "AMpreset18.name": "AM 18", "AMpreset19.name": "AM 19",
    "AMpreset20.name": "AM 20", "AMpreset21.name": "AM 21", "AMpreset22.name": "AM 22", "AMpreset23.name": "AM 23", "AMpreset24.name": "AM 24", "AMpreset25.name": "AM 25", "AMpreset26.name": "AM 26", "AMpreset27.name": "AM 27", "AMpreset28.name": "AM 28", "AMpreset29.name": "AM 29", "AMpreset30.name": "AM 30", "FMpreset1.name": "FM 1", "FMpreset2.name": "FM 2", "FMpreset3.name": "FM 3", "FMpreset4.name": "FM 4", "FMpreset5.name": "FM 5", "FMpreset6.name": "FM 6", "FMpreset7.name": "FM 7", "FMpreset8.name": "FM 8", "FMpreset9.name": "FM 9",
    "FMpreset10.name": "FM 10", "FMpreset11.name": "FM 11", "FMpreset12.name": "FM 12", "FMpreset13.name": "FM 13", "FMpreset14.name": "FM 14", "FMpreset15.name": "FM 15", "FMpreset16.name": "FM 16", "FMpreset17.name": "FM 17", "FMpreset18.name": "FM 18", "FMpreset19.name": "FM 19", "FMpreset20.name": "FM 20", "FMpreset21.name": "FM 21", "FMpreset22.name": "FM 22", "FMpreset23.name": "FM 23", "FMpreset24.name": "FM 24", "FMpreset25.name": "FM 25", "FMpreset26.name": "FM 26", "FMpreset27.name": "FM 27", "FMpreset28.name": "FM 28", "FMpreset29.name": "FM 29",
    "FMpreset30.name": "FM 30"
}; function validateStationName(c, a) { return null !== a && 0 < a.replace(/\s+/g, "").length ? a : _defaultStationNameTable[c] } var _defaultInputNameTable = { "BD.inputname": "BD/DVD", "SAT.inputname": "SAT/CATV", "GAME.inputname": "GAME", "STB.inputname": "STB", "VIDEO.inputname": "VIDEO", "AUX.inputname": "AUX", "TV.inputname": "TV", "CD.inputname": "SA-CD/CD" }; function validateInputName(c, a) { return null !== a && 0 < a.replace(/\s+/g, "").length ? a : _defaultInputNameTable[c] }
function validateInputSrc(c) { "dvd" === c ? c = "bd" : "catv" === c ? c = "sat" : "sacd" === c && (c = "cd"); return c } function setDisabled(c, a) { var b = document.getElementById(c); b && (b.disabled = a) }
function parseEventAvailable(c) {
    var a; a = c[0]; setDisabled("level.CR", 0 === (a & 64) ? !0 : !1); setDisabled("level.SW", 0 === (a & 32) ? !0 : !1); setDisabled("audio.dualmono", 0 === (a & 4) ? !0 : !1); var b = c[1]; setDisabled("audio.dll", 0 === (b & 128) ? !0 : !1); setDisabled("audio.soundoptimizer", 0 === (b & 64) ? !0 : !1); a = 0 === (b & 16) ? !0 : !1; setDisabled("bass.front", a); setDisabled("treble.front", a); setDisabled("custompreset1.useFrontbass", a); setDisabled("custompreset1.frontbass", a); setDisabled("custompreset1.useFronttreble", a); setDisabled("custompreset1.fronttreble",
        a); setDisabled("custompreset2.useFrontbass", a); setDisabled("custompreset2.frontbass", a); setDisabled("custompreset2.useFronttreble", a); setDisabled("custompreset2.fronttreble", a); setDisabled("custompreset3.useFrontbass", a); setDisabled("custompreset3.frontbass", a); setDisabled("custompreset3.useFronttreble", a); setDisabled("custompreset3.fronttreble", a); setDisabled("custompreset4.useFrontbass", a); setDisabled("custompreset4.frontbass", a); setDisabled("custompreset4.useFronttreble", a); setDisabled("custompreset4.fronttreble",
            a); setDisabled("speaker.centerliftup", 0 === (b & 4) ? !0 : !1); b = c[2]; setDisabled("speaker.autocal.start", 0 === (b & 128) ? !0 : !1); setDisabled("speaker.calibrationtype", 0 === (b & 32) ? !0 : !1); setDisabled("speaker.apm", 0 === (b & 16) ? !0 : !1); setDisabled("audio.puredirect", 0 === (b & 8) ? !0 : !1); a = 0 === (b & 4) ? !0 : !1; setDisabled("speaker.testtone.off", a); setDisabled("speaker.testtone.auto", a); setDisabled("speaker.testtone.fl", a); setDisabled("speaker.testtone.fr", a); setDisabled("speaker.testtone.c", a); setDisabled("speaker.testtone.sl",
                a); setDisabled("speaker.testtone.sr", a); setDisabled("speaker.testtone.sb", a); setDisabled("speaker.testtone.sbl", a); setDisabled("speaker.testtone.sbr", a); setDisabled("speaker.testtone.h1l", a); setDisabled("speaker.testtone.h1r", a); setDisabled("speaker.testtone.h2l", a); setDisabled("speaker.testtone.h2r", a); setDisabled("speaker.testtone.sw", a); setDisabled("speaker.SBassign", 0 === (b & 1) ? !0 : !1); a = c[3]; setDisabled("size.front", 0 === (a & 128) ? !0 : !1); setDisabled("size.center", 0 === (a & 64) ? !0 : !1); setDisabled("size.surround",
                    0 === (a & 32) ? !0 : !1); setDisabled("size.fronthigh", 0 === (a & 16) ? !0 : !1); setDisabled("crossover.front", 0 === (a & 8) ? !0 : !1); setDisabled("crossover.center", 0 === (a & 4) ? !0 : !1); setDisabled("crossover.surround", 0 === (a & 2) ? !0 : !1); setDisabled("crossover.fronthigh", 0 === (a & 1) ? !0 : !1); a = c[4]; setDisabled("audio.swlpf", 0 === (a & 32) ? !0 : !1); setDisabled("hdmi.zonepriority", 0 === (a & 16) ? !0 : !1); setDisabled("hdmi.cec", 0 === (a & 1) ? !0 : !1); b = c[5]; a = 0 === (b & 128) ? !0 : !1; setDisabled("bass.center", a); setDisabled("treble.center", a); setDisabled("custompreset1.useCenterbass",
                        a); setDisabled("custompreset1.centerbass", a); setDisabled("custompreset1.useCentertreble", a); setDisabled("custompreset1.centertreble", a); setDisabled("custompreset2.useCenterbass", a); setDisabled("custompreset2.centerbass", a); setDisabled("custompreset2.useCentertreble", a); setDisabled("custompreset2.centertreble", a); setDisabled("custompreset3.useCenterbass", a); setDisabled("custompreset3.centerbass", a); setDisabled("custompreset3.useCentertreble", a); setDisabled("custompreset3.centertreble", a); setDisabled("custompreset4.useCenterbass",
                            a); setDisabled("custompreset4.centerbass", a); setDisabled("custompreset4.useCentertreble", a); setDisabled("custompreset4.centertreble", a); a = 0 === (b & 64) ? !0 : !1; setDisabled("bass.surround", a); setDisabled("treble.surround", a); setDisabled("custompreset1.useSurroundbass", a); setDisabled("custompreset1.surroundbass", a); setDisabled("custompreset1.useSurroundtreble", a); setDisabled("custompreset1.surroundtreble", a); setDisabled("custompreset2.useSurroundbass", a); setDisabled("custompreset2.surroundbass", a); setDisabled("custompreset2.useSurroundtreble",
                                a); setDisabled("custompreset2.surroundtreble", a); setDisabled("custompreset3.useSurroundbass", a); setDisabled("custompreset3.surroundbass", a); setDisabled("custompreset3.useSurroundtreble", a); setDisabled("custompreset3.surroundtreble", a); setDisabled("custompreset4.useSurroundbass", a); setDisabled("custompreset4.surroundbass", a); setDisabled("custompreset4.useSurroundtreble", a); setDisabled("custompreset4.surroundtreble", a); a = 0 === (b & 32) ? !0 : !1; setDisabled("bass.fronthigh", a); setDisabled("treble.fronthigh",
                                    a); setDisabled("hdmi.fastview", 0 === (b & 16) ? !0 : !1); 7 > c.length || (b = c[6], a = 0 === (b & 32) ? !0 : !1, setDisabled("level.SL", a), setDisabled("level.SR", a), a = 0 === (b & 8) ? !0 : !1, setDisabled("level.SBL", a), setDisabled("level.SBR", a), a = 0 === (b & 4) ? !0 : !1, setDisabled("level.FHL", a), setDisabled("level.FHR", a), setDisabled("audio.drangecomp", 0 === (b & 2) ? !0 : !1), 8 > c.length || (b = c[7], setDisabled("audio.inceilingmode", 0 === (b & 16) ? !0 : !1), a = 0 === (b & 8) ? !0 : !1, setDisabled("speaker.ceilingheight", a), setDisabled("speaker.ceilingheight.sub",
                                        a), setDisabled("hdmi.zone2audioout", 0 === (b & 4) ? !0 : !1), 9 > c.length || (b = c[8], a = 0 === (b & 128) ? !0 : !1, setDisabled("distance.FL", a), setDisabled("distance.FL.sub", a), setDisabled("distance.FR", a), setDisabled("distance.FR.sub", a), a = 0 === (b & 64) ? !0 : !1, setDisabled("distance.CR", a), setDisabled("distance.CR.sub", a), a = 0 === (b & 32) ? !0 : !1, setDisabled("distance.SL", a), setDisabled("distance.SL.sub", a), setDisabled("distance.SR", a), setDisabled("distance.SR.sub", a), a = 0 === (b & 16) ? !0 : !1, setDisabled("distance.SB", a), setDisabled("distance.SB.sub",
                                            a), a = 0 === (b & 8) ? !0 : !1, setDisabled("distance.SBL", a), setDisabled("distance.SBL.sub", a), setDisabled("distance.SBR", a), setDisabled("distance.SBR.sub", a), a = 0 === (b & 4) ? !0 : !1, setDisabled("distance.FHL", a), setDisabled("distance.FHL.sub", a), setDisabled("distance.FHR", a), setDisabled("distance.FHR.sub", a), a = 0 === (b & 2) ? !0 : !1, setDisabled("distance.SW", a), setDisabled("distance.SW.sub", a), 9 > c.length || (b = c[9], a = 0 === (b & 128) ? !0 : !1, setDisabled("zone2.presetvoldb", a), setDisabled("zone2.presetvolstep", a), a = 0 === (b & 64) ? !0 :
                                                !1, setDisabled("zone3.presetvoldb", a), setDisabled("zone3.presetvolstep", a), setDisabled("zone2.lineout", 0 === (b & 32) ? !0 : !1), setDisabled("zone3.lineout", 0 === (b & 16) ? !0 : !1), a = 0 === (b & 8) ? !0 : !1, setDisabled("trigger1.BD", a), setDisabled("trigger1.SAT", a), setDisabled("trigger1.GAME", a), setDisabled("trigger1.STB", a), setDisabled("trigger1.VIDEO", a), setDisabled("trigger1.AUX", a), setDisabled("trigger1.TV", a), setDisabled("trigger1.CD", a), setDisabled("trigger1.FM", a), setDisabled("trigger1.AM", a), setDisabled("trigger1.hdmiA",
                                                    a), setDisabled("trigger1.hdmiB", a), setDisabled("trigger1.hdmiOff", a), a = 0 === (b & 4) ? !0 : !1, setDisabled("trigger2.BD", a), setDisabled("trigger2.SAT", a), setDisabled("trigger2.GAME", a), setDisabled("trigger2.STB", a), setDisabled("trigger2.VIDEO", a), setDisabled("trigger2.AUX", a), setDisabled("trigger2.TV", a), setDisabled("trigger2.CD", a), setDisabled("trigger2.FM", a), setDisabled("trigger2.AM", a), setDisabled("trigger2.hdmiA", a), setDisabled("trigger2.hdmiB", a), setDisabled("trigger2.hdmiOff", a), a = 0 === (b & 2) ? !0 : !1,
                                                setDisabled("trigger3.BD", a), setDisabled("trigger3.SAT", a), setDisabled("trigger3.GAME", a), setDisabled("trigger3.STB", a), setDisabled("trigger3.VIDEO", a), setDisabled("trigger3.AUX", a), setDisabled("trigger3.TV", a), setDisabled("trigger3.CD", a), setDisabled("trigger3.FM", a), setDisabled("trigger3.AM", a), setDisabled("trigger3.hdmiA", a), setDisabled("trigger3.hdmiB", a), setDisabled("trigger3.hdmiOff", a), 0 === (b & 1) && parent.main && (parent.main.location.href = "unavailable.html"), setDisabled("speaker.H1assign", 0 ===
                                                    (c[10] & 4) ? !0 : !1), b = c[11], setDisabled("size.height1", 0 === (b & 128) ? !0 : !1), setDisabled("size.height2", 0 === (b & 64) ? !0 : !1), setDisabled("crossover.height1", 0 === (b & 32) ? !0 : !1), setDisabled("crossover.height2", 0 === (b & 16) ? !0 : !1), a = 0 === (b & 8) ? !0 : !1, setDisabled("level.H1L", a), setDisabled("level.H1R", a), a = 0 === (b & 4) ? !0 : !1, setDisabled("level.H2L", a), setDisabled("level.H2R", a), a = 0 === (b & 2) ? !0 : !1, setDisabled("distance.H1L", a), setDisabled("distance.H1L.sub", a), setDisabled("distance.H1R", a), setDisabled("distance.H1R.sub",
                                                        a), a = 0 === (b & 1) ? !0 : !1, setDisabled("distance.H2L", a), setDisabled("distance.H2L.sub", a), setDisabled("distance.H2R", a), setDisabled("distance.H2R.sub", a), c = c[12], a = 0 === (c & 128) ? !0 : !1, setDisabled("bass.height1", a), setDisabled("treble.height1", a), setDisabled("custompreset1.useHeight1bass", a), setDisabled("custompreset1.height1bass", a), setDisabled("custompreset1.useHeight1treble", a), setDisabled("custompreset1.height1treble", a), setDisabled("custompreset2.useHeight1bass", a), setDisabled("custompreset2.height1bass",
                                                            a), setDisabled("custompreset2.useHeight1treble", a), setDisabled("custompreset2.height1treble", a), setDisabled("custompreset3.useHeight1bass", a), setDisabled("custompreset3.height1bass", a), setDisabled("custompreset3.useHeight1treble", a), setDisabled("custompreset3.height1treble", a), setDisabled("custompreset4.useHeight1bass", a), setDisabled("custompreset4.height1bass", a), setDisabled("custompreset4.useHeight1treble", a), setDisabled("custompreset4.height1treble", a), a = 0 === (c & 64) ? !0 : !1, setDisabled("bass.height2",
                                                                a), setDisabled("treble.height2", a), setDisabled("custompreset1.useHeight2bass", a), setDisabled("custompreset1.height2bass", a), setDisabled("custompreset1.useHeight2treble", a), setDisabled("custompreset1.height2treble", a), setDisabled("custompreset2.useHeight2bass", a), setDisabled("custompreset2.height2bass", a), setDisabled("custompreset2.useHeight2treble", a), setDisabled("custompreset2.height2treble", a), setDisabled("custompreset3.useHeight2bass", a), setDisabled("custompreset3.height2bass", a), setDisabled("custompreset3.useHeight2treble",
                                                                    a), setDisabled("custompreset3.height2treble", a), setDisabled("custompreset4.useHeight2bass", a), setDisabled("custompreset4.height2bass", a), setDisabled("custompreset4.useHeight2treble", a), setDisabled("custompreset4.height2treble", a), setDisabled("speaker.reloc", 0 === (c & 32) ? !0 : !1), setDisabled("speaker.srpos", 0 === (c & 16) ? !0 : !1), setDisabled("hdmi.linked", 0 === (c & 8) ? !0 : !1)))))
} function initializeCommon() { "console" in window || (window.console = {}, window.console.log = function (c) { }) }
function setInnerText(c, a) { c.textContent ? c.textContent = a : c.innerText = a };
