# lovelace_gen
{%- set sources_cols = 5 %}
{%- set sources_rows = 2 %}
{% set sources = [
  {'entity':'switch.xbox_source', 'color': 'rgba(14, 122, 13)', 'template': '../templates/remote_icon_button.yaml'},
  {'entity':'switch.playstation_source', 'color': 'rgba(102, 92, 190)', 'template': '../templates/remote_icon_button.yaml'},
  {'entity':'switch.roku_source', 'color': 'rgba(105, 58, 147)', 'template': '../templates/remote_image_button.yaml', 'image': '/local/images/roku.png'},
  {'entity':'switch.nintendo_switch_source', 'color': 'rgba(228, 0, 15)', 'template': '../templates/remote_icon_button.yaml'},
  {'entity':'switch.chromecast_source', 'color': 'rgba(66,133,244)', 'template': '../templates/remote_icon_button.yaml'},
  {'entity':'switch.alexa_source', 'color': 'rgba(49, 196, 243)', 'template': '../templates/remote_icon_button.yaml', 'icon': 'fab:amazon'},
] %}

title: Remote Settings
path: remote_settings
icon: mdi:cog
visible: {{ visible | default(false) }}
cards:

- type: horizontal-stack
  cards:
    - !include '../templates/buttons/edge.yaml'
    - !include
      - ../templates/headers/navigator.yaml
      - name: Remote Settings
        back_path: remote
    - !include '../templates/buttons/edge.yaml'

# SOURCE

- type: vertical-stack
  cards:
  - !include
    - ../templates/headers/label.yaml
    - content: 'Source'
  {%- for i in range(sources_cols * sources_rows) %}
  {%- set source = sources[i] %}
    {%- if i % sources_cols == 0 %}
  - type: horizontal-stack
    cards:
    - !include '../templates/spacer_edge.yaml'
    {%- endif %}
    {% if source %}
    - !include
      {%- if source.template %}
      - {{ source.template }}
      {%- else %}
      - '../templates/remote/harmony/toggle.yaml'
      {%- endif %}
      - entity: {{ source.entity }}
        color: {{ source.color }}
        {%- if source.icon is defined %}
        icon: {{ source.icon }}
        {%- endif %}
        {%- if source.image is defined %}
        image: {{ source.image }}
        {%- endif %}
    {% else %}
    - !include '../templates/buttons/spacer.yaml'
    {% endif %}
    {%- if i % sources_cols == sources_cols - 1 %}
    - !include '../templates/spacer_edge.yaml'
    {%- endif %}
  {%- endfor %}